version: "3.8"

volumes:
  postgres:


services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migrations:
    image: mrkunei/django-stripe-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  api:
    image: mrkunei/django-stripe-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env
    command: python manage.py runserver 0.0.0.0:8000
