# Generated by Django 4.1.7 on 2023-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('percent_off', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.PositiveIntegerField(default=1, help_text='price in dollars cents')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='usd', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('inclusive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='usd', max_length=3)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='core.discount')),
                ('items', models.ManyToManyField(related_name='order', to='core.item')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='core.tax')),
            ],
        ),
    ]
