# Generated by Django 4.1.7 on 2023-02-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
